version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   restart: always
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_PASSWORD=password
  #     - DB_USER=admin
  #     - DB_PORT=27017
  #   command: air



  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ecom'
      # So you don't have to use root, but you can if you like
      MYSQL_ROOT_PASSWORD: 'asdf'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:

